# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

# e.g. Rails.application.secrets.google_oauth_secret

development:
  secret_key_base: 0ea18472970ae2b618c7cf15f57e7e9356e7fc5cfe705918c84337a258a6840ad11110ef8f54306a96ce7dd3695b23763e4ad45f05c815f5b399e8cc3c674cd4
  devise_secret_key: c09ce6e292f178eb2e48cdbc975d65eae65ec826bdaf6d2603e64744cde27b371256f6b65cadfcad18d09bd26aa73b543c256ad8f4a7971ecb57a7030e93b9db

test:
  secret_key_base: a0be20c6914cab0fedcd69f3c12726c9add040e5e826fcbeb556ac14dc0b255416a975ac5b51a8d0d72eae102a2a3c83f95152909d6e079f49783a985fa0dde2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["MOVIENIGHT_SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>

shared:
  gmail_smtp_password: <%= ENV["MOVIENIGHT_GMAIL_SMTP_PASSWORD"] %>
  tmdb_api_key: <%= ENV["MOVIENIGHT_TMDB_API_KEY"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  google_oauth_client_id: <%= ENV["GOOGLE_OAUTH_CLIENT_ID"] %>
  google_oauth_secret: <%= ENV["GOOGLE_OAUTH_SECRET"] %>
